theme: jekyll-theme-cayman
 
# Setup
title:        [Learn in 60 seconds]
description: [bite sized learning you can use]
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Tanya Gupta
  url:        http://learnin60seconds.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown  



